controller_manager:
  ros__parameters:
    update_rate: 30  # Hz
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_base_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_base_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    
    wheel_separation: 0.24
    wheel_radius: 0.045

    publish_rate: 50.0
    
    base_frame_id: base_link
    odom_frame_id: odom
    use_stamped_vel: false